#!/usr/local/bin/perl

if ($#ARGV != 0) {
    die "Usage: log2tlg basename";
}

$BASE = shift;


$skipping = 0;
$skip_autoload = 0;

$LTOPDIR = $ENV{'LTOPDIR'};

#
# skip everything until START-TEST-LOG is seen
#

while (<>) {
    /^START-TEST-LOG/ && last;
}


while (<>) {
    # if END-TEST-LOG is seen, terminate
    /^END-TEST-LOG/ && last;

    # if OMIT is seen, skip until TIMO
    if (/^OMIT/) {
	$skipping++;
	next;
    } elsif (/^TIMO/) {
	$skipping--;
	next;
    }

    next if $skipping;

    # if environment variable LTOPDIR is set, replace beginning of paths
    if ($LTOPDIR) {
        s#$LTOPDIR/latex2/#../../#g;
    }

#    s/$BASE(\.lvt)?//og;
    s/(\.\/)?$BASE//og;

    # if we are running the autoload test suite, the environment variable
    # TLG_PREFIX is set

    if ($ENV{'TLG_PREFIX'}) {

	if ($skip_autoload) {
	    /^\)/ && ($skip_autoload = 0);
	    next;
	} elsif (/^(.*)\(auto(err|fss1|out1|pict|tabg)\.sty$/) {
	    $skip_autoload = 1;
	    ($_ = $1) =~ s/\s+$//;
	    $_ = "$_\n";
	}

    }

    # skip filedate lines
    /[^<][0-9][0-9][0-9][0-9]\/[0-9][0-9]\/[0-9][0-9]/ && next;

    # skip ident lines from .fd files
    if (/\([^ ]*fd/.../^[ ]*\)/) {
        next;
    }


    # skip \openin/\openout lines in web2c 7.x
    if (/^\\open(in|out)\d+ = /) {
	# skip empty line
	$_ = <>;
	next;
    }

    # remove messy DOS CR at end of line
    s/\r+$//;

    # zap ./ at begin of filename
    s/\(\.\//\(/g;

    # change err message of older pdfTeX which doesn't know so many dimensions ...
    s/cm, mm, dd, cc, bp, or sp/cm, mm, dd, cc, nd, nc, bp, or sp/g;

    # zap "on line <num>" and replace with "on line ..."
    s/on line [0-9]*/on line \.\.\./g;

    # zap <num> on various allocations
    # s/=\\box[0-9]*/=\\box\.\.\./;
    # s/=\\count[0-9]*/=\\count\.\.\./;
    # s/=\\dimen[0-9]*/=\\dimen\.\.\./;
    # s/=\\muskip[0-9]*/=\\muskip\.\.\./;
    # s/=\\skip[0-9]*/=\\skip\.\.\./;
    # s/=\\toks[0-9]*/=\\toks\.\.\./;

    # zap "[1{/.../pdftex.map}]"
    s/\[1\{[\w\/\-]*\/pdftex\.map\}\]//;

    # do not print empty lines
    print if ! /^\s*$/;
}
