#! /bin/sh 
#
# This file is part of the validate package.
# ------------------------------------------
#
# Makes a .tlg file from a test file with the extension .lvt
# Run's tex two times to get aux files etc.
#
# usage: maketlg <format name> <test file base> [translation table]
# or
# usage: maketlg <test file base>
#
# In the later case a format called latfs will be used. 
# This is LaTeX with nfss running on my machine. If you don't this
# use the first form.




# check number of args and set format etc.
#
if [ $# = 1 ]
then
LATEX=latfs
BASE=`basename $1 .lvt`
else
if [ $# = 3 ]
then
TRANSLATE="--translate-file=$3"
fi
LATEX="etex $TRANSLATE -efmt=$1"
BASE=`basename $2 .lvt`
fi

LANG=C ; export LANG

# remove all kind of rubbish
#
rm -f $BASE.log $BASE.au?  $BASE.tmp.tlg $BASE.tlg.diff $BASE.dvi
rm -f $BASE.lvt.log $BASE.lvt.au?  $BASE.lvt.dvi
rm -f $BASE.glo $BASE.idx  $BASE.lof $BASE.toc $BASE.lot
rm -f $BASE.lvt.glo $BASE.lvt.idx  $BASE.lvt.lof $BASE.lvt.toc $BASE.lvt.lot

# run TeX twice with chosen format
#
yes "" | $LATEX $BASE.lvt
yes "" | $LATEX $BASE.lvt

if test -r $BASE.lvt.log ; then LOG=$BASE.lvt.log ; else LOG=$BASE.log ; fi

# remove stuff from the log which is of no interest and save the result
# in tmp file
#
test "$LTOPDIR" && EXTRA=-e\ s#$LTOPDIR/latex2/#../../#
#sed -e "1,/START-TEST-LOG/d"  \
#    -e "/END-TEST-LOG/,//d"   \
#    -e "/OMIT/,/TIMO/d"       \
#    -e "s/$BASE//"            \
#    -e "/([^ ]*fd/,/^[ ]*)/d" \
#    -e "\![^<][0-9][0-9][0-9][0-9]/[0-9][0-9]/[0-9][0-9]!d" \
#    $EXTRA \
#                              $BASE.log > ${TLG_PREFIX}$BASE.tlg
rm -f ${TLG_PREFIX}$BASE.tlg
perl `dirname $0`/log2tlg $BASE   < $LOG > ${TLG_PREFIX}$BASE.tlg

echo TLG file produced for $BASE in `pwd`/$BASE.tlg

#
